import = ["~/.config/alacritty/keybindings.toml"]

[window]
    opacity = 0.75
    decorations = "None"
    blur = true
[font]
    normal = { family = "0xProtoNerdFontMono", style = "Regular"}
    size = 8
