$MAIN = rgba(1E1738ee)
$ACCENT1 = rgba(770175ee)
$ACCENT2 = rgba(E435B8ee)
$DARK = rgba(2A2A31ff)
$LIGHT = rgba(FDE8E9ff)

$FOREGROUND = rgba(a9b1dcff)
$BACKGROUND = rgba(1a1b2cff)
$CURSORCOLOR = rgba(c0caf5ff)
$SELECTIONBACKGROUND = rgba(28344aff)
$BLACK = rgba(414868ff)
$RED = rgba(f7768eff)
$GREEN = rgba(73dacaff)
$YELLOW = rgba(e0af68ff)
$BLUE = rgba(7aa2f7ff)
$PURPLE = rgba(bb9af7ff)
$CYAN = rgba(7dcfffff)
$WHITE = rgba(c0caf5ff)
$BRIGHTBLACK = rgba(414868ff)
$BRIGHTRED = rgba(f7768eff)
$BRIGHTGREEN = rgba(73dacaff)
$BRIGHTYELLOW = rgba(e0af68ff)
$BRIGHTBLUE = rgba(7aa2f7ff)
$BRIGHTPURPLE = rgba(bb9af7ff)
$BRIGHTCYAN = rgba(7dcfffff)
$BRIGHTWHITE = rgba(c0caf5ff)

# {
# 	"name": "Tokyo Night",
# 	"foreground": "#a9b1dc",
# 	"background": "#1a1b2c",
# 	"cursorColor": "#c0caf5",
# 	"selectionBackground": "#28344a",
# 	"black": "#414868",
# 	"red": "#f7768e",
# 	"green": "#73daca",
# 	"yellow": "#e0af68",
# 	"blue": "#7aa2f7",
# 	"purple": "#bb9af7",
# 	"cyan": "#7dcfff",
# 	"white": "#c0caf5",
# 	"brightBlack": "#414868",
# 	"brightRed": "#f7768e",
# 	"brightGreen": "#73daca",
# 	"brightYellow": "#e0af68",
# 	"brightBlue": "#7aa2f7",
# 	"brightPurple": "#bb9af7",
# 	"brightCyan": "#7dcfff",
# 	"brightWhite": "#c0caf5"
# }
