# preload = /home/griffdawg/Downloads/pexels-evgeny-tchebotarev-1058775-2187605.jpg
wallpaper {
  monitor = eDP-1
  path = /home/griffdawg/Downloads/pexels-evgeny-tchebotarev-1058775-2187605.jpg
  fit_mode = cover
}

